-- Persistent incidents generated by failed or manual dorsal operations.

create type public.incident_status as enum ('pending', 'review', 'resolved');
create type public.incident_severity as enum ('low', 'medium', 'high');

create table if not exists public.incidents (
  id uuid primary key default gen_random_uuid(),
  code text not null unique default ('INC-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  kind text not null,
  title text not null,
  description text not null,
  status public.incident_status not null default 'pending',
  severity public.incident_severity not null default 'medium',
  user_id uuid references public.profiles (id) on delete set null,
  user_email text not null,
  dorsal_number smallint not null references public.dorsals (number) on delete restrict,
  source text not null default 'claim_dorsal',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists incidents_touch_updated_at on public.incidents;
create trigger incidents_touch_updated_at
before update on public.incidents
for each row execute function public.touch_updated_at();

create or replace function public.register_incident(
  p_user_id uuid,
  p_dorsal_number smallint,
  p_kind text,
  p_title text,
  p_description text,
  p_status public.incident_status default 'pending',
  p_severity public.incident_severity default 'medium',
  p_source text default 'claim_dorsal',
  p_details jsonb default '{}'::jsonb
)
returns public.incidents
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_incident public.incidents%rowtype;
begin
  select *
  into v_profile
  from public.profiles
  where id = p_user_id;

  if not found then
    raise exception 'Profile not found';
  end if;

  insert into public.incidents (
    kind,
    title,
    description,
    status,
    severity,
    user_id,
    user_email,
    dorsal_number,
    source,
    details
  )
  values (
    p_kind,
    p_title,
    p_description,
    p_status,
    p_severity,
    p_user_id,
    v_profile.email,
    p_dorsal_number,
    p_source,
    p_details
  )
  returning * into v_incident;

  return v_incident;
end;
$$;

create policy incidents_select_admin
  on public.incidents
  for select
  using (public.is_admin());

create policy incidents_manage_admin
  on public.incidents
  for all
  using (public.is_admin())
  with check (public.is_admin());

alter table public.incidents enable row level security;

insert into public.incidents (
  kind,
  title,
  description,
  status,
  severity,
  user_id,
  user_email,
  dorsal_number,
  source,
  details
)
values
  (
    'duplicate_assignment',
    'Dorsal ya asignado',
    'Se intentó reservar un dorsal que ya tenía una asignación activa.',
    'review',
    'high',
    null,
    'ana.martin@example.com',
    12,
    'seed',
    jsonb_build_object('seed', true)
  ),
  (
    'dorsal_locked',
    'Dorsal bloqueado solicitado',
    'El usuario solicitó el dorsal 27, que está bloqueado por la administración y requiere revisión.',
    'pending',
    'medium',
    null,
    'javier.lopez@example.com',
    27,
    'seed',
    jsonb_build_object('seed', true)
  ),
  (
    'manual_resolution',
    'Asignación resuelta por soporte',
    'Se revisó el caso del dorsal 44, se corrigió el estado y la incidencia quedó cerrada correctamente.',
    'resolved',
    'low',
    null,
    'maria.garcia@example.com',
    44,
    'seed',
    jsonb_build_object('seed', true)
  )
on conflict (code) do nothing;

create or replace function public.claim_dorsal(p_child_id uuid, p_dorsal_number smallint)
returns public.dorsal_assignments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings public.contest_settings%rowtype;
  v_child public.children%rowtype;
  v_dorsal public.dorsals%rowtype;
  v_assignment public.dorsal_assignments%rowtype;
  v_incident_status public.incident_status;
  v_incident_severity public.incident_severity;
  v_incident_kind text;
  v_incident_title text;
  v_incident_description text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select *
  into v_settings
  from public.contest_settings
  where id = 1;

  if not coalesce(v_settings.is_enabled, false)
     or v_settings.opens_at is null
     or v_settings.closes_at is null
     or now() < v_settings.opens_at
     or now() > v_settings.closes_at then
    raise exception 'Contest is closed';
  end if;

  select *
  into v_child
  from public.children
  where id = p_child_id;

  if not found then
    raise exception 'Child not found';
  end if;

  if v_child.parent_id <> auth.uid() and not public.is_admin() then
    raise exception 'Child does not belong to the current user';
  end if;

  select *
  into v_dorsal
  from public.dorsals
  where number = p_dorsal_number
  for update;

  if not found then
    raise exception 'Dorsal not found';
  end if;

  if v_dorsal.is_locked then
    raise exception 'Dorsal is locked';
  end if;

  if exists (
    select 1
    from public.dorsal_assignments
    where dorsal_number = p_dorsal_number
  ) then
    raise exception 'Dorsal already assigned';
  end if;

  if exists (
    select 1
    from public.dorsal_assignments
    where child_id = p_child_id
  ) then
    raise exception 'Child already has a dorsal';
  end if;

  insert into public.dorsal_assignments (dorsal_number, child_id, assigned_by)
  values (p_dorsal_number, p_child_id, auth.uid())
  returning * into v_assignment;

  insert into public.assignment_attempts (parent_id, child_id, dorsal_number, success)
  values (auth.uid(), p_child_id, p_dorsal_number, true);

  return v_assignment;
exception
  when others then
    if sqlerrm = 'Contest is closed' then
      v_incident_kind := 'contest_closed';
      v_incident_status := 'pending';
      v_incident_severity := 'medium';
      v_incident_title := 'Intento fuera de ventana';
      v_incident_description := 'Se intentó asignar un dorsal cuando el concurso estaba cerrado.';
    elsif sqlerrm = 'Child not found' then
      v_incident_kind := 'child_missing';
      v_incident_status := 'review';
      v_incident_severity := 'medium';
      v_incident_title := 'Hijo no registrado';
      v_incident_description := 'La cuenta intentó resolver una asignación sin un hijo asociado.';
    elsif sqlerrm = 'Child does not belong to the current user' then
      v_incident_kind := 'ownership_mismatch';
      v_incident_status := 'review';
      v_incident_severity := 'high';
      v_incident_title := 'Hijo no vinculado al usuario';
      v_incident_description := 'La incidencia apunta a un menor que no pertenece a la cuenta activa.';
    elsif sqlerrm = 'Dorsal not found' then
      v_incident_kind := 'dorsal_missing';
      v_incident_status := 'review';
      v_incident_severity := 'medium';
      v_incident_title := 'Dorsal inexistente';
      v_incident_description := 'Se solicitó un dorsal que no existe en el catálogo.';
    elsif sqlerrm = 'Dorsal is locked' then
      v_incident_kind := 'dorsal_locked';
      v_incident_status := 'pending';
      v_incident_severity := 'low';
      v_incident_title := 'Dorsal bloqueado';
      v_incident_description := 'Se intentó reservar un dorsal bloqueado por la administración.';
    elsif sqlerrm = 'Dorsal already assigned' then
      v_incident_kind := 'duplicate_assignment';
      v_incident_status := 'review';
      v_incident_severity := 'high';
      v_incident_title := 'Dorsal ya asignado';
      v_incident_description := 'Dos intentos de reserva han chocado sobre el mismo dorsal.';
    elsif sqlerrm = 'Child already has a dorsal' then
      v_incident_kind := 'duplicate_child_assignment';
      v_incident_status := 'review';
      v_incident_severity := 'high';
      v_incident_title := 'El menor ya tiene dorsal';
      v_incident_description := 'Se intentó asignar más de un dorsal al mismo menor.';
    else
      v_incident_kind := 'unexpected_error';
      v_incident_status := 'review';
      v_incident_severity := 'high';
      v_incident_title := 'Error en la asignación';
      v_incident_description := sqlerrm;
    end if;

    perform public.register_incident(
      auth.uid(),
      p_dorsal_number,
      v_incident_kind,
      v_incident_title,
      v_incident_description,
      v_incident_status,
      v_incident_severity,
      'claim_dorsal',
      jsonb_build_object(
        'child_id', p_child_id,
        'error', sqlerrm
      )
    );

    insert into public.assignment_attempts (parent_id, child_id, dorsal_number, success, failure_reason)
    values (auth.uid(), p_child_id, p_dorsal_number, false, sqlerrm);
    raise;
end;
$$;